# Generated by Django 6.0.1 on 2026-07-01 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('requires_lab', models.BooleanField(default=False)),
                ('requires_followup', models.BooleanField(default=False)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('followup_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('avg_consultation_time', models.IntegerField(default=10)),
                ('is_available', models.BooleanField(default=True)),
                ('max_queue_size', models.IntegerField(default=5)),
                ('is_throttled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('slot_type', models.CharField(choices=[('morning', 'Morning (9:00-11:00)'), ('afternoon', 'Afternoon (12:00-14:00)'), ('evening', 'Evening (15:00-17:00)')], max_length=20)),
                ('max_tokens', models.IntegerField(editable=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.doctorprofile')),
            ],
            options={
                'unique_together': {('doctor', 'date', 'slot_type')},
            },
        ),
        migrations.CreateModel(
            name='FollowupRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exempt_within_days', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=150)),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('fee_pending', 'Fee Pending'), ('fee_paid', 'Fee Paid'), ('in_queue', 'In Queue'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='ordered', max_length=20)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='core.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='lab_reports/%Y/%m/')),
                ('findings', models.TextField(blank=True)),
                ('is_same_day', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('lab_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='core.laborder')),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'role': 'lab_technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThrottleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('throttled', 'Throttled'), ('resumed', 'Resumed')], max_length=10)),
                ('queue_length_at_trigger', models.IntegerField()),
                ('threshold_at_trigger', models.IntegerField()),
                ('triggered_by', models.CharField(choices=[('system', 'System'), ('admin', 'Admin')], default='system', max_length=10)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='throttle_logs', to='core.consultationslot')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_phone', models.CharField(max_length=15)),
                ('patient_address', models.CharField(blank=True, max_length=255)),
                ('token_number', models.CharField(max_length=10)),
                ('estimated_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('checked_in', 'Checked In'), ('consulting', 'Consulting'), ('pending_lab', 'Pending Lab'), ('pending_pharmacy', 'Pending Pharmacy'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='booked', max_length=20)),
                ('checkin_status', models.CharField(blank=True, choices=[('present', 'Present'), ('missed', 'Missed')], max_length=10, null=True)),
                ('is_elderly', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('is_followup', models.BooleanField(default=False)),
                ('fee_exempted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_started_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_ended_at', models.DateTimeField(blank=True, null=True)),
                ('original_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_tokens', to='core.token')),
                ('patient', models.ForeignKey(blank=True, limit_choices_to={'role': 'patient'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
                ('receptionist', models.ForeignKey(blank=True, limit_choices_to={'role': 'receptionist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_tokens', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='core.consultationslot')),
            ],
            options={
                'ordering': ['estimated_time'],
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_date', models.DateField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('normal', 'Normal')], default='normal', max_length=10)),
                ('queue_status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('in_progress', 'In Progress'), ('done', 'Done'), ('skipped', 'Skipped')], default='waiting', max_length=20)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('wait_minutes', models.IntegerField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='core.doctorprofile')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='core.consultationslot')),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='core.token')),
            ],
            options={
                'verbose_name_plural': 'Queue Entries',
                'ordering': ['token__created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=150)),
                ('dosage', models.CharField(blank=True, max_length=50)),
                ('frequency', models.CharField(blank=True, max_length=50)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('instructions', models.CharField(blank=True, max_length=255)),
                ('dispensed', models.BooleanField(default=False)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.consultation')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='core.token')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('dispensing', 'Dispensing'), ('done', 'Done')], default='waiting', max_length=20)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_bill', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_collected', models.BooleanField(default=False)),
                ('pharmacist', models.ForeignKey(blank=True, limit_choices_to={'role': 'pharmacist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_queue_entries', to=settings.AUTH_USER_MODEL)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_queue_entry', to='core.token')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('consultation_fee', 'Consultation Fee'), ('lab_fee', 'Lab Fee'), ('pharmacy_fee', 'Pharmacy Fee')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived')], default='pending', max_length=10)),
                ('waiver_reason', models.CharField(blank=True, max_length=150)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.token')),
            ],
        ),
        migrations.CreateModel(
            name='LabQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('done', 'Done')], default='waiting', max_length=20)),
                ('lab_fee_paid', models.BooleanField(default=False)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lab_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='core.laborder')),
                ('technician', models.ForeignKey(blank=True, limit_choices_to={'role': 'lab_technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_queue_entries', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_queue_entries', to='core.token')),
            ],
        ),
        migrations.AddField(
            model_name='laborder',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='core.token'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='core.token'),
        ),
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('total_tokens_issued', models.IntegerField(default=0)),
                ('total_checkins', models.IntegerField(default=0)),
                ('total_no_shows', models.IntegerField(default=0)),
                ('avg_wait_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('avg_consultation_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('peak_queue_length', models.IntegerField(blank=True, null=True)),
                ('peak_hour', models.IntegerField(blank=True, null=True)),
                ('throttle_events_count', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.consultationslot')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.doctorprofile')),
            ],
            options={
                'verbose_name_plural': 'Daily Analytics',
                'unique_together': {('report_date', 'doctor', 'slot')},
            },
        ),
    ]
