# Generated by Django 4.2.11 on 2026-06-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctorprofile_is_throttled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='fee_exempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='original_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.token'),
        ),
        migrations.AlterField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('checked_in', 'Checked In'), ('consulting', 'Consulting'), ('completed', 'Completed'), ('missed', 'Missed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
    ]
