# Generated by Django 6.0.1 on 2026-07-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_otpverification_slotoptimizationrecommendation'),
        ('core', '0004_consultation_laborder_doctorprofile_qualification_and_more'),
    ]

    operations = [
    ]
