# Generated by Django 4.2.11 on 2026-07-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_labqueueentry_technician_and_more'),
        ('core', '0004_consultation_laborder_doctorprofile_qualification_and_more'),
    ]

    operations = [
    ]
