# Generated by Django 4.2.11 on 2026-07-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_otpverification_slotoptimizationrecommendation'),
        ('core', '0005_merge_20260704_2106'),
    ]

    operations = [
    ]
