# Generated by Django 6.0.1 on 2026-07-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20260706_1358'),
        ('core', '0008_consultationslot_unique_date_slot'),
    ]

    operations = [
    ]
