# Generated by Django 6.0.1 on 2026-07-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20260706_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyqueueentry',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('dispensing', 'Dispensing'), ('ready', 'Ready for Pickup'), ('done', 'Done')], default='waiting', max_length=20),
        ),
    ]
