# Generated by Django 6.0.1 on 2026-07-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_laborder_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slottypeconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
