# Generated by Django 6.0.1 on 2026-07-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_slottypeconfig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('checked_in', 'Checked In'), ('consulting', 'Consulting'), ('pending_lab', 'Pending Lab'), ('pending_pharmacy', 'Pending Pharmacy'), ('completed', 'Completed'), ('expired', 'No-show'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
    ]
