# Generated by Django 6.0.1 on 2026-07-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_serial', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Patient serial counter',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='patient_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
