# Generated by Django 6.0.1 on 2026-07-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_apitoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='apitoken',
            new_name='accounts_ap_user_id_8492a1_idx',
            old_name='accounts_ap_user_id_6e8f0a_idx',
        ),
    ]
